[project]
name    = "std"
version = "0.1.0"
author  = "Xast Platform"
modules = [
    "Std.Alloc",
    "Std.Bool",
    "Std.Error",
    "Std.Num",
    "Std.Ops",
    "Std.Option",
    "Std.OptionResult",
    "Std.Result",
    "Std.String",
]

[api]
labels = []
components = []